config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get '/busca', to: 'search#games', as: 'search'

  scope path_names: { new: 'novo', edit: 'editar' } do
    get '/auctions/finished', to: 'games#finished_auctions', as: 'finished_auctions', path: 'clicks/finalizados'
    get '/auctions/scheduled', to: 'games#scheduled_auctions', as: 'scheduled_auctions', path: 'clicks/agendados'

    resources :auctions, only: %i(show), path: 'clicks' do
      get :verify_status
      resources :auction_bids, only: %i(create), as: :bids
      get '/prize_claim', to: 'prize_claims#new', as: 'prize_claim', path: 'reivindicar'
    end

    get '/best_guesses/finished', to: 'games#finished_best_guesses', as: 'finished_best_guesses', path: 'super-palpites/finalizados'
    get '/best_guesses/scheduled', to: 'games#scheduled_best_guesses', as: 'scheduled_best_guesses', path: 'super-palpites/agendados'
    get '/super-palpites', to: 'games#best_guesses', as: :best_guesses
    get '/torneio-palpites', to: 'games#best_guess_tournaments', as: :best_guess_tournaments
    get '/super-clicks', to: 'games#auctions', as: :auctions
    get '/torneio-clicks', to: 'games#auction_tournaments', as: :auction_tournaments
    resources :auction_attempts, only: :destroy

    resources :best_guesses, only: %i(show), path: 'super-palpites' do
      get :feedback
      get :unfinished_attempt_redirect
      get :verify_status
      resources :best_guess_attempt, only: %i(create edit update destroy), path: 'tentativas', as: :attempts
      get '/prize_claim', to: 'prize_claims#new', as: 'prize_claim', path: 'reivindicar'
    end

    resources :games, only: :index, path: 'jogos'

    resources :prize_claims, only: %i(create index), as: :prize_claims, path: 'premios'

    if Rails.env.development? || Rails.env.staging?
      get '/styleguide', to: 'pages#styleguide'
    end

    get '/termos', to: 'pages#terms', as: 'terms'
    get '/como-funciona', to: 'pages#how_it_works', as: 'how_it_works'
    get '/contato', to: 'pages#contact', as: 'contact'
    post '/contato', to: 'pages#send_contact', as: nil

    resources :plans, only: %i(index), path: 'planos'
    resources :checkouts, only: %i(new create), path: 'comprar' do
      get :success, path: 'sucesso'
    end
    post "iugu/#{Rails.application.secrets.iugu_url}/notification", to: 'plans#notification', as: nil
    resources :purchases, only: %i(index), path: 'compras'

    devise_for :users, path: "usuarios", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'senha', registration: 'registro', sign_up: 'cadastro' }, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
    devise_scope :user do
      get '/mudar-senha', to: 'users/registrations#edit', as: :change_password
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/best_guess_attempt.rb
class BestGuessAttempt < ActiveRecord::Base
  attr_accessor :joined

  before_validation :set_value, if: :best_guess

  after_create :discount_user_credits
  after_create :happens_at_to_best_guess, if: :tournament?
  before_destroy :rollback_user_credits, if: :tournament?

  belongs_to :user
  belongs_to :best_guess
  has_many :statement_answers, dependent: :destroy
  has_many :statements, through: :statement_answers

  accepts_nested_attributes_for :statement_answers

  validates :user, :best_guess, presence: true
  validates :user_id, uniqueness: { scope: :best_guess_id, message: 'Você já deu um palpite neste jogo' }
  validate :best_guess_is_active
  validate :user_have_credits, on: :create

  scope :finished, -> { where.not(finished_at: nil) }
  scope :with_correct_answers, -> (best_guess_id) { joins(:statements).where('"statement_answers"."value" = "statements"."answer" AND "statement_answers"."statement_id" = "statements"."id" AND "statements"."best_guess_id" = ?', best_guess_id).order('"best_guess_attempts"."score" DESC, "best_guess_attempts"."finished_at" - "best_guess_attempts"."started_at" ASC') }

  delegate :tournament?, to: :best_guess

  def finish_time
    finished_at && finished_at - started_at
  end

  def user_have_credits
    return true if user && user.credits > 0 && best_guess && user.credits >= best_guess.join_cost_in_credits
    errors.add(:base, :must_have_credits)
  end

  def set_value
    self.value_in_credits ||= best_guess.join_cost_in_credits
  end

  def best_guess_is_active
    return true if best_guess && best_guess.active?
    errors.add(:base, :is_not_active)
  end

  def discount_user_credits
    user.decrement!(:credits, value_in_credits) if user
  end

  def happens_at_to_best_guess
    if best_guess.best_guess_attempts.count == best_guess.players
      best_guess.happens_at = DateTime.now
      best_guess.ends_at = best_guess.duration_time.minutes.from_now
      best_guess.save(validate: false)
    end
  end

  private

  def rollback_user_credits
    user.increment!(:credits, value_in_credits) if user && tournament?
  end
end

app/controllers/best_guess_attempt_controller.rb
class BestGuessAttemptController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized, except: %i(edit update create)

  rescue_from Pundit::NotAuthorizedError, with: :missing_credits

  def create
    best_guess = BestGuess.find(params[:best_guess_id])
    attempt = BestGuessAttempt.new(user: current_user, best_guess: best_guess)
    if !BestGuessAttemptPolicy.new(current_user, attempt).user_have_credits?
      return redirect_to best_guess_path(best_guess), flash: { alert: I18n.t('activerecord.errors.models.auction_bid.attributes.base.must_have_credits') }
    end
    if best_guess.tournament?
      if BestGuessAttemptPolicy.new(current_user, attempt).tournament_not_full?
        authorize(attempt)
      else
        return redirect_to best_guess_path(best_guess), flash: { alert: 'Torneio já começou' }
      end
    else
      authorize(attempt)
    end
    if attempt.save
      attempt.joined = true
      GameNotification.publish(attempt)
      if best_guess.tournament?
        return redirect_to best_guess_path(best_guess)
      else
        return redirect_to best_guess_path(best_guess), flash: { notice: 'Inscrito com sucesso! Clique em START para começar seu palpite' }
      end
    else
      return redirect_to best_guess_path(best_guess), flash: { alert: attempt.errors.messages.values.join('; ') }
    end
  end

  def edit
    @best_guess = BestGuess.find(params[:best_guess_id])
    @attempt = BestGuessAttempt.find(params[:id])
    if policy(@attempt).edit?
      authorize(@attempt)
    else
      redirect_to best_guess_path(@best_guess), flash: { alert: 'Não autorizado' }
    end
    @attempt.started_at ||= DateTime.now
    @attempt.save
    @attempt.reload
    @statements = @best_guess.statements.shuffle
    @statements.each do |statement|
      @attempt.statement_answers.build(statement: statement)
    end
  end

  def update
    @best_guess = BestGuess.find(params[:best_guess_id])
    @attempt = BestGuessAttempt.find(params[:id])
    if policy(@attempt).update?
      authorize(@attempt)
    else
      redirect_to best_guess_path(@best_guess), flash: { alert: 'Não autorizado' }
    end
    if @attempt.update_attributes(permitted_params.merge(finished_at: Time.now))
      GameNotification.publish(@attempt)
      redirect_to best_guess_path(@best_guess)
    else
      render :edit
    end
  end


  def destroy
    best_guess = BestGuess.find(params[:best_guess_id])
    attempt = BestGuessAttempt.find(params[:id])
    authorize(attempt)
    if attempt.destroy
      GameNotification.publish(attempt)
    end
    redirect_to root_path
  end

  private

  def permitted_params
    params.require(:best_guess_attempt).permit(statement_answers_attributes: [:statement_id, :value])
  end

  def missing_credits
    if request.xhr?
      render json: { errors: [I18n.t('best_guesses.missing_credits')] }, status: :payment_required
    else
      flash[:alert] = I18n.t('best_guesses.missing_credits')
      redirect_to(request.referrer || root_path)
    end
  end
end

app/views/best_guess_attempt/edit.html.slim
- timezone = (Time.zone.utc_offset + TZInfo::Timezone.get(Time.zone.tzinfo.name).current_period.std_offset) / 60

section.features
  .container
    .column.-md-4-5.u-centered
      .row
        .column.-md-fill.boxCard.js-box
          .box-badge.boxCard-badge.-highlight.-best-guess[class="#{@best_guess.tournament? ? '-blue' : '-yellow'}"]
            span.badge-game
              i.fa.fa-badge
              | #{@best_guess.tournament? ? ' Torneio ' : ' Super '}
            span.badge-gameType palpite
          .row
            .columns.-md-2-5
              .boxCard-image.cover-image.flexEmbed.-is16by9 style="background-image: url(#{@best_guess.image.url})"
              .boxCard-timer.js-spinner.-big.-countdown.-colorInverse
                i.fa.fa-refresh.spinner
              .boxCard-timer.-big.-countdown.-colorInverse.u-hide
                .js-countDown[data-ends="#{@best_guess.ends_at.to_i}" data-starts="#{@attempt.started_at.to_i}", data-attempt-edit="true" data-redirect-url="#{best_guess_unfinished_attempt_redirect_path(@best_guess)}"]
                span.boxCard-timer-text para encerrar a partida
            .columns.-md-3-5
              h1.boxCard-title = @best_guess.title
              .boxCard-timer.-small.-best-guess.js-countup[data-timezone="#{timezone}" data-starts="#{@attempt.started_at.to_i * 1000}"]
              .questionBox
                h2.questionBox-title = @best_guess.question
                = simple_form_for @attempt, url: best_guess_attempt_path(@best_guess, @attempt) do |f|
                  span.questionBox-desc Selecione as opções abaixo que você considera correta
                  ul.questionBox-answers class="#{'-with-images' if @best_guess.decorate.statements_have_image?}"
                    = f.simple_fields_for :statement_answers do |statement_answer|
                      li.questionBox-answers-item.js-optionListSelect
                        = statement_answer.input :statement_id, input_html: { value: statement_answer.object.statement_id }, as: :hidden
                        = statement_answer.check_box :value, id: "answer-#{statement_answer.object.statement_id}"
                        = statement_answer.label :value, for: "answer-#{statement_answer.object.statement_id}", class: 'questionBox-answers-answer'
                          - if statement_answer.object.statement.image.present?
                            = image_tag statement_answer.object.statement.image, class: 'questionBox-asnwers-image'
                          span = statement_answer.object.statement.content
                  .questionBox-action
                    - if policy(@attempt).update?
                      button.btn.-btn-block.text-largest[style="margin-bottom: 15px" class="#{@best_guess.tournament? ? '-btn-line-primary' : '-btn-line-secondary'}" data-disable-with="Enviando..."] Confirmar palpite
                    - else
                      = link_to 'Acabou o tempo. Voltar para o jogo', best_guess_path(@best_guess), class: "btn -btn-block text-largest #{@best_guess.tournament? ? '-btn-line-primary' : '-btn-line-secondary'}"

javascript:
  (function() {
    var counter = $('.js-countup');
    var start = parseInt(counter.data('starts'));
    var diff = ServerDate.now() - Date.now();
    start = start - diff;
    counter.countdown('option', { since: new Date(start) });
  }).call(this);