config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get '/busca', to: 'search#games', as: 'search'

  scope path_names: { new: 'novo', edit: 'editar' } do
    get '/auctions/finished', to: 'games#finished_auctions', as: 'finished_auctions', path: 'clicks/finalizados'
    get '/auctions/scheduled', to: 'games#scheduled_auctions', as: 'scheduled_auctions', path: 'clicks/agendados'

    resources :auctions, only: %i(show), path: 'clicks' do
      get :verify_status
      resources :auction_bids, only: %i(create), as: :bids
      get '/prize_claim', to: 'prize_claims#new', as: 'prize_claim', path: 'reivindicar'
    end

    get '/best_guesses/finished', to: 'games#finished_best_guesses', as: 'finished_best_guesses', path: 'super-palpites/finalizados'
    get '/best_guesses/scheduled', to: 'games#scheduled_best_guesses', as: 'scheduled_best_guesses', path: 'super-palpites/agendados'
    get '/super-palpites', to: 'games#best_guesses', as: :best_guesses
    get '/torneio-palpites', to: 'games#best_guess_tournaments', as: :best_guess_tournaments
    get '/super-clicks', to: 'games#auctions', as: :auctions
    get '/torneio-clicks', to: 'games#auction_tournaments', as: :auction_tournaments
    resources :auction_attempts, only: :destroy

    resources :best_guesses, only: %i(show), path: 'super-palpites' do
      get :feedback
      get :unfinished_attempt_redirect
      get :verify_status
      resources :best_guess_attempt, only: %i(create edit update destroy), path: 'tentativas', as: :attempts
      get '/prize_claim', to: 'prize_claims#new', as: 'prize_claim', path: 'reivindicar'
    end

    resources :games, only: :index, path: 'jogos'

    resources :prize_claims, only: %i(create index), as: :prize_claims, path: 'premios'

    if Rails.env.development? || Rails.env.staging?
      get '/styleguide', to: 'pages#styleguide'
    end

    get '/termos', to: 'pages#terms', as: 'terms'
    get '/como-funciona', to: 'pages#how_it_works', as: 'how_it_works'
    get '/contato', to: 'pages#contact', as: 'contact'
    post '/contato', to: 'pages#send_contact', as: nil

    resources :plans, only: %i(index), path: 'planos'
    resources :checkouts, only: %i(new create), path: 'comprar' do
      get :success, path: 'sucesso'
    end
    post "iugu/#{Rails.application.secrets.iugu_url}/notification", to: 'plans#notification', as: nil
    resources :purchases, only: %i(index), path: 'compras'

    devise_for :users, path: "usuarios", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'senha', registration: 'registro', sign_up: 'cadastro' }, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
    devise_scope :user do
      get '/mudar-senha', to: 'users/registrations#edit', as: :change_password
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/views/partials/_badge_svg.html.slim
svg viewbox=("0 0 1194 461") xmlns="http://www.w3.org/2000/svg" zoomandpan="disable" 
  path d=("M0 0h1194v461H0z") fill="none"
  path d=("M501.016 225.984l-.032-137-137 .032z") stroke="#000" stroke-width="0" vector-effect="non-scaling-stroke" 

app/views/partials/_footer.html.slim
footer.footer
  .container.-mobile
    .row
      .columns.-md-fill
        h1.footer-brand
          = image_tag 'logo.png'

        .footer-menuLft
          ul
            li.menu-item
              = link_to 'Termos de uso', terms_path, class: 'menu-link'

            li.menu-item
              = link_to 'Site da Sumatra' , 'http://sumatrasurfersbeer.com/', class: 'menu-link'

        nav.footer-menu
          ul.menu
            / TODO add real links
            li.menu-item.-social
              = mail_to 'sumatra@bugsystem.com.br', class: 'menu-social-link' do
                = icon('envelope')
            li.menu-item.-social
              = link_to 'https://www.facebook.com/Sumatra-Surfers-Beer-1695196434128489/?fref=ts', class: 'menu-social-link' do
                = icon('facebook')
            li.menu-item.-social
              = link_to 'https://www.instagram.com/SumatraSurfersBeer/', class: 'menu-social-link' do
                = icon('instagram')
    .row.u-marginTop20
      .columns.-md-fill
        .footer-copy.small.u-textCenter
          | SUMATRA &copy; Copyright 2016 - Todos os direitos reservados. Tecnologia
          = link_to ' BUGX', 'http://bugx.funcommerce.com.br', class: 'text-white'
          = link_to ' by Bug System', "http://www.bugsystem.com.br", class: 'text-white'

app/views/partials/_games.html.slim
.container
  h2.heading.u-textCenter[style="margin-top: 0"] Aprenda a Jogar
  .row
    .column.-md-3-5.u-centered
      p.text-larger.text-neutral.u-textCenter
        |
        span style="#{'display: none !important;' if params[:controller] == 'best_guesses' || params[:controller] == 'auctions'}"
      .div style="#{'display: none !important;' if params[:controller] == 'best_guesses'}"
        h2.u-textUp.text-yellow.u-textCenter Jogo do Click
        p.text-larger.text-neutral.u-textCenter No Jogo do Click você disputa de forma emocionante uma oferta por um preço incrível. Para participar basta ter um saldo de virabits e dar seus Clicks nos jogos que desejar, você vai ganhar se manter seu Click até o final do contador regressivo. Mas fique esperto a cada novo Click o contador reiniciará sua contagem regressiva, dê seu Click e garanta para ele permanecer até o crônometro acabar para você ser o VENCEDOR!
        h4.text-largest.u-textCenter.u-marginTop10
          span.u-textBold.text-neutral Aprenda como jogar
    .container.-small style="#{'display: none !important;' if params[:controller] == 'best_guesses'}"
      .row
        .columns.-md-1-3
          .feature.-arrow
            .feature-image.-square
              span = image_tag('comclick1.jpg')
            h4.feature-title.-small
              | Começou a contagem, agora é a a melhor hora de dar seus clicks!
        .columns.-md-1-3
          .feature.-arrow
            .feature-image.-square
              span = image_tag('comclick2.jpg')
            h4.feature-title.-small
              | Seu Click está Ganhando? Agora é só esperar o crônometro zerar para ganhar, segure a adrenalina :O
        .columns.-md-1-3
          .feature.-arrow
            .feature-image.-square
              span = image_tag('comclick3.jpg')
            h4.feature-title.-small
              | Você venceu! Agora é só alegria, você já pode resgatar sua Oferta por um preço incrível /o/

    .column.-md-3-5.u-centered style="#{'display: none !important;' if params[:controller] == 'auctions'}"
      h2.u-textUp.text-yellow.u-textCenter Jogo do Palpite
      p.text-larger.text-neutral.u-textCenter Dê seu melhor Palpite para levar uma Sumatra! Para participar basta ter um saldo de Sumabits e dar seus Palpites nos jogos que desejar, você vai ganhar se acertar o maior número de alternativa corretas no menor tempo de tentativa. Mas fique ligado quando for participar, iremos cronometrar o tempo que você vai levar para escolher suas resposta, termine o mais rápido possível e garanta sua chance de ser o VENCEDOR!
      h4.text-largest.u-textCenter.u-marginTop10
        span.u-textBold.text-neutral Aprenda como jogar
    .container.-small style="#{'display: none !important;' if params[:controller] == 'auctions'}"
      .row
        .columns.-md-1-3
          .feature.-arrow
            .feature-image.-square
              span = image_tag('compalp1.jpg')
            h4.feature-title.-small
              | Observe o Tema e nossa Dica sobre o desafio e dê seu palpite.
        .columns.-md-1-3
          .feature.-arrow
            .feature-image.-square
              span = image_tag('compalp2.jpg')
            h4.feature-title.-small
              | Realize seu palpite o mais rápido possível! Acertando o maior número de respostas corretas no menor tempo você ganha :)
        .columns.-md-1-3
          .feature.-arrow
            .feature-image.-square
              span = image_tag('compalp3.jpg')
            h4.feature-title.-small
              | Agora é só esperar o jogo terminar para descobrir se o seu palpite é o vencedor para levar sua Sumatra por um preço incrível /o/
  h4.text-largest.u-textCenter.u-marginTop100

app/views/partials/_header.html.slim
header.header
  .container
    .row
      .u-clearfix
        h1.header-brand
          = link_to image_tag('logo.png'),  root_url
        nav.header-menu class="#{'-noBtn' if user_signed_in?}"
          .menu-toggle
            span
            span
            span
          ul.menu.-desktop class="#{'-noBtn' if user_signed_in?}"
            li.menu-item
              = link_to t('.play_now'), root_path(anchor: 'playnow'), class: 'menu-link'
            - if user_signed_in?
              .header-widget
                .header-credit
                  .small Sumabits
                  h3.u-textYellow
                    span.u-textBold S
                    i.fa.fa-btc.u-fontSize110 &nbsp;
                    span.js-user-credits = current_user.credits
              li.menu-item.dropdown-toggle
                a.btn.-btn-line-header.u-textLow.js-gameStarted
                  span.fa.fa-user.u-marginRgt10
                  span = truncate(current_user.username, length: 15)
                  span.fa.fa-caret-down.u-marginLft10
                ul.dropdown
                  li.dropdown-item
                    = link_to 'Editar Perfil', edit_user_registration_path, class: 'dropdown-link'
                  li.dropdown-item
                    = link_to 'Prêmios', prize_claims_path, class: 'dropdown-link'
                  li.dropdown-item
                    = link_to 'Histórico', purchases_path, class: 'dropdown-link'
                  li.dropdown-item
                    = link_to t('sign_out'), destroy_user_session_path, method: :delete, class: 'dropdown-link'
            - else
              li.menu-item
                a.menu-link data-trig="modal" data-remote="#{new_user_session_path}" data-target="#sign-in-modal" = t('sign_in')
              - unless params[:controller] == 'users/registrations' && (params[:action] == 'new' || params[:action] == 'create')
                li.menu-item
                  a.btn.-btn-line-header data-trig="modal" data-remote="#{new_user_registration_path}" data-target="#sign-up-modal" = t('sign_up')
      ul.menu.-mobile class="#{'-noBtn' if user_signed_in?}"
        li.menu-item
          = link_to t('.play_now'), root_path(anchor: 'playnow'), class: 'menu-link'
        - if user_signed_in?
          li.menu-item
            h6.u-noMargin.text-yellow.menu-link.js-gameStarted
              = current_user.username
              span.u-textBold  - V
              i.fa.fa-btc.u-fontSize110 &nbsp;
              span.js-user-credits = current_user.credits
          li.menu-item
            = link_to 'Prêmios', prize_claims_path, class: 'menu-link'
          li.menu-item
            = link_to 'Editar Perfil', edit_user_registration_path, class: 'menu-link'
          li.menu-item
            = link_to t('sign_out'), destroy_user_session_path, method: :delete, class: 'menu-link'
        - else
          li.menu-item
            = link_to t('sign_in'), new_user_session_path, class: 'menu-link'
          li.menu-item
            = link_to t('sign_up'), new_user_registration_path, class: 'btn -btn-line-primary', style: 'color: #fff'
  nav.header-submenu
    .container
      ul.menu.-desktop.u-textRgt
        li.submenu-item.-dropdown.dropdown-toggle
          = link_to 'Todos os Jogos', best_guesses_path, class: 'submenu-link'
        li.submenu-item
          = simple_form_for :search, url: search_path, method: :get do |f|
            - value = params[:search].present? ? params[:search][:query] : nil
            = f.input :query, label: false, placeholder: 'Digite a sua busca...', input_html: {value: value}
            = f.button :button, class: 'menu-linkSearch js-toggle-search' do
              span.fa.fa-search
      ul.menu.-mobile
        li.submenu-item
          = link_to 'Todos os Jogos', best_guesses_path, class: 'submenu-link'
        li.submenu-item
          = simple_form_for :search, url: search_path, method: :get do |f|
            - value = params[:search].present? ? params[:search][:query] : nil
            = f.input :query, label: false, placeholder: 'Digite a sua busca...', input_html: {class: 'mobile-search', value: value}
        li.submenu-item
          a.menu-linkSearch.u-textCenter.js-toggle-search href=""
            span.fa.fa-search

/ Modals
.modal-wrapper#sign-up-modal
  .modal.-small
    .modal-header
      span.modal-close data-close="modal" &times;
    .modal-body
.modal-wrapper#sign-in-modal
  .modal.-small
    .modal-header
      span.modal-close data-close="modal" &times;
    .modal-body