config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get '/busca', to: 'search#games', as: 'search'

  scope path_names: { new: 'novo', edit: 'editar' } do
    get '/auctions/finished', to: 'games#finished_auctions', as: 'finished_auctions', path: 'clicks/finalizados'
    get '/auctions/scheduled', to: 'games#scheduled_auctions', as: 'scheduled_auctions', path: 'clicks/agendados'

    resources :auctions, only: %i(show), path: 'clicks' do
      get :verify_status
      resources :auction_bids, only: %i(create), as: :bids
      get '/prize_claim', to: 'prize_claims#new', as: 'prize_claim', path: 'reivindicar'
    end

    get '/best_guesses/finished', to: 'games#finished_best_guesses', as: 'finished_best_guesses', path: 'super-palpites/finalizados'
    get '/best_guesses/scheduled', to: 'games#scheduled_best_guesses', as: 'scheduled_best_guesses', path: 'super-palpites/agendados'
    get '/super-palpites', to: 'games#best_guesses', as: :best_guesses
    get '/torneio-palpites', to: 'games#best_guess_tournaments', as: :best_guess_tournaments
    get '/super-clicks', to: 'games#auctions', as: :auctions
    get '/torneio-clicks', to: 'games#auction_tournaments', as: :auction_tournaments
    resources :auction_attempts, only: :destroy

    resources :best_guesses, only: %i(show), path: 'super-palpites' do
      get :feedback
      get :unfinished_attempt_redirect
      get :verify_status
      resources :best_guess_attempt, only: %i(create edit update destroy), path: 'tentativas', as: :attempts
      get '/prize_claim', to: 'prize_claims#new', as: 'prize_claim', path: 'reivindicar'
    end

    resources :games, only: :index, path: 'jogos'

    resources :prize_claims, only: %i(create index), as: :prize_claims, path: 'premios'

    if Rails.env.development? || Rails.env.staging?
      get '/styleguide', to: 'pages#styleguide'
    end

    get '/termos', to: 'pages#terms', as: 'terms'
    get '/como-funciona', to: 'pages#how_it_works', as: 'how_it_works'
    get '/contato', to: 'pages#contact', as: 'contact'
    post '/contato', to: 'pages#send_contact', as: nil

    resources :plans, only: %i(index), path: 'planos'
    resources :checkouts, only: %i(new create), path: 'comprar' do
      get :success, path: 'sucesso'
    end
    post "iugu/#{Rails.application.secrets.iugu_url}/notification", to: 'plans#notification', as: nil
    resources :purchases, only: %i(index), path: 'compras'

    devise_for :users, path: "usuarios", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'senha', registration: 'registro', sign_up: 'cadastro' }, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
    devise_scope :user do
      get '/mudar-senha', to: 'users/registrations#edit', as: :change_password
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/controllers/best_guesses_controller.rb
class BestGuessesController < ApplicationController
  after_action :verify_authorized, except: %i(verify_status unfinished_attempt_redirect feedback)

  def show
    @best_guess = BestGuess.find(params[:id])
    authorize @best_guess
    @attempt = BestGuessAttempt.find_by(user: current_user, best_guess: @best_guess)
    @highlight_last_bids = @best_guess.best_guess_attempts
    @winner_attempt = BestGuessAttempt.find_by(user: @best_guess.winner, best_guess: @best_guess) if @best_guess.winner.present?
    @correct_awnsers = @best_guess.statements
  end

  def verify_status
    best_guess = BestGuess.find(params[:best_guess_id])
    best_guess.check_winner
    render nothing: true
  end

  def unfinished_attempt_redirect
    best_guess = BestGuess.find(params[:best_guess_id])
    redirect_to best_guess_path(best_guess), alert: 'O jogo acabou e seu palpite não foi contabilizado. Mais sorte da próxima vez.'
  end

  def feedback
    @best_guess = BestGuess.find(params[:best_guess_id])
    @correct_awnsers = @best_guess.statements
    @attempt = BestGuessAttempt.find_by(user: current_user, best_guess: @best_guess)
    @winner_attempt = BestGuessAttempt.find_by(user: @best_guess.winner, best_guess: @best_guess) if @best_guess.winner.present?
    render partial: 'feedback'
  end
end

app/views/best_guesses/_best_guess.html.slim
- timezone = (Time.zone.utc_offset + TZInfo::Timezone.get(Time.zone.tzinfo.name).current_period.std_offset) / 60

- content_for :active_box, flush: true
  .box-footer
    .box-info.js-spinner.-big.-countdown
      i.fa.fa-refresh.spinner
    .box-info.-big.-countdown.u-hide.js-parent
      span.little-words Termina em
      .js-countDown.js-withActive[data-ends="#{best_guess.ends_at.to_i}" data-timezone="#{timezone}" data-starts="#{best_guess.happens_at.to_i}" data-tournament="#{best_guess.tournament? && best_guess.happens_at.nil?}" data-end-step="#{best_guess.duration_time}"]
    .box-marketValue.u-textBold.u-textCenter
      span = "valor de mercado: "
      span.u-textBlack = number_to_currency best_guess.market_price
    .box-price
      span.text-small.u-marginRgt5 Pontos
      span.box-price-big.value.js-priceValue = best_guess.partial_value / 100.0
    .box-action.join-in.js-bid-action[data-costing="#{best_guess.join_cost_in_credits}" data-increase="#{number_to_currency best_guess.increase_value/100.to_f}" data-type="BestGuess"]
      - if user_signed_in?
        - unless params[:controller] == 'best_guess' && params[:action] == 'show'
          - if policy(BestGuessAttempt.new(user: current_user, best_guess: best_guess)).join?
            button.js-btn-bid-cost.btn.-btn-block.u-marginTop15[data-trig="modal" data-target="#best-guess-modal-#{best_guess.id}" class="#{best_guess.tournament? ? '-btn-line-primary' : '-btn-line-secondary'}"] Dar Palpite
            = button_to 'O jogo já começou', best_guess_path(best_guess), class: 'btn -btn-inverse -btn-block u-hide js-followGame fullRoom', method: :get
          - else
            - attempt = best_guess.best_guess_attempts.find_by(user: current_user)
            - if attempt && attempt.finished_at.nil?
              = button_to 'Start', edit_best_guess_attempt_path(best_guess, attempt), class: 'btn -btn-line-danger -btn-block u-marginTop15', method: :get
            - elsif attempt
              span.-btn-block.boxCard-counter.u-marginTop15[disabled="true" title="Você já participou" style="padding-top: 10px; padding-bottom: 10px; border-radius: 6px;"] = "Seu tempo foi: #{Time.at(attempt.finish_time).utc.strftime("%Mm %Ss %3Nms") if attempt}"
            - else
              = button_to 'O jogo já começou', best_guess_path(best_guess), class: 'btn -btn-inverse -btn-block u-marginTop15 fullRoom', method: :get
      - else
        = button_to new_user_session_path, class: "u-marginTop15 btn #{best_guess.tournament? ? '-btn-line-primary' : '-btn-line-secondary'} -btn-block js-btn-bid-cost", method: :get do
          / texto botão usuário não logado (jogo ativo)
          = best_guess.tournament? ? 'Participar' : 'Dar Palpite'
        = button_to 'O jogo já começou', best_guess_path(best_guess), class: 'u-marginTop15 btn -btn-inverse -btn-block u-hide js-followGame fullRoom', method: :get

- content_for :scheduled_box, flush: true
  .box-footer.-scheduled.js-boxFooter
    .box-info.js-spinner.-big.-countdown.js-countDown.u-hide.js-withScheduled[data-ends="#{best_guess.ends_at.to_i}" data-timezone="#{timezone}" data-starts="#{best_guess.happens_at.to_i}" data-tournament="#{best_guess.tournament? && best_guess.happens_at.nil?}" data-end-step="#{best_guess.duration_time}"]
      i.fa.fa-refresh.spinner
    - if best_guess.tournament? && best_guess.happens_at.nil?
      .u-textBold.js-Players[style="font-size: 2rem;text-align: center;margin-bottom: -2px; padding-top:2px"]
        span = best_guess.best_guess_attempts.count
        | /#{best_guess.players}
        p[style="font-size: 0.85rem;margin: 0"] JOGADORES
    .box-info.js-happensText.u-hide
      - if !best_guess.tournament? && best_guess.happens_at
        span.box-info-small Começa em
        span.box-info-big
          span.u-textBold = l best_guess.happens_at, format: :concise
    .box-marketValue.u-textBold.u-textCenter
      span = "valor de mercado: "
      span.u-textBlack = number_to_currency best_guess.market_price
    .box-price
      .box-price-big
        span S
        span.fa.fa-btc.u-fontSize110 &nbsp;
        span #{best_guess.join_cost_in_credits}
    .box-action.js-bid-action[data-costing="#{best_guess.join_cost_in_credits}" data-increase="#{number_to_currency best_guess.increase_value/100.to_f}" data-tournament="#{best_guess.tournament? && best_guess.happens_at.nil?}" data-type="BestGuess"]
      - if user_signed_in?
        - unless params[:controller] == 'best_guess' && params[:action] == 'show'
          - if policy(BestGuessAttempt.new(user: current_user, best_guess: best_guess)).join?
            button.js-btn-bid-cost.btn.-btn-block.u-marginTop15[data-trig="modal" data-target="#best-guess-modal-#{best_guess.id}" class="#{best_guess.tournament? ? '-btn-line-primary -btn-inverse' : '-btn-line-scheduled'}"]
              / botão agendado pra usuário logado(TORNEIO) (botão de participar quando o jogo ainda não começou)
              = best_guess.tournament? ? 'inscreva-se' : 'Agendado'
            = button_to 'O jogo já começou', best_guess_path(best_guess), class: 'btn -btn-inverse -btn-block u-hide js-followGame fullRoom', method: :get
          - else
            - attempt = best_guess.best_guess_attempts.find_by(user: current_user, finished_at: nil)
            - if attempt
              - if policy(attempt).destroy?
                = link_to 'Cancelar inscrição', best_guess_attempt_path(best_guess, attempt), class: 'js-cancelAttemptBtn btn -btn-danger u-marginTop15', method: :delete, style: 'font-size: 1rem; width: 100%; padding-top: 10px; padding-bottom: 9px;', title: 'Disponível apenas enquanto não começar o jogo'
              = button_to 'Start', edit_best_guess_attempt_path(best_guess, attempt), class: "btn -btn-line-danger -btn-block u-marginTop15 #{'u-hide' if policy(attempt).destroy?}", method: :get
            - else
              button.js-btn-bid-cost.btn.-btn-block.u-marginTop15[data-trig="modal" data-target="#best-guess-modal-#{best_guess.id}" class="#{best_guess.tournament? ? '-btn-line-primary -btn-inverse' : '-btn-line-scheduled'}"]
                | Dar Palpite
              = button_to 'O jogo já começou', best_guess_path(best_guess), class: 'btn -btn-inverse -btn-block u-marginTop15 fullRoom', method: :get
      - else
        = button_to new_user_session_path, class: "u-marginTop15 btn #{'-btn-line-primary -btn-inverse' if best_guess.tournament?} -btn-block js-btn-bid-cost", method: :get do
          / texto botão agendado pra usuário não logado (botão de participar quando o jogo ainda não começou)
          = best_guess.tournament? ? 'Participar' : 'Agendado'
        = button_to 'O jogo já começou', best_guess_path(best_guess), class: 'u-marginTop15 btn -btn-inverse -btn-block u-hide js-followGame fullRoom', method: :get

- content_for :winner_box, flush: true
  .box-notify.-box-notify-success
    .box-info.-box-info-notify.-big
      i.fa.fa-trophy
      .box-notify-text.-winner Venceu
    .box-marketValue.u-textBold.u-textCenter.u-noMargin
      span.u-textWhite = "valor de mercado: "
      span.u-textWhite = number_to_currency best_guess.market_price
    .box-price.-box-price-notify.-winner
      span.box-price-big.-box-price-big-notify.js-priceValue = number_to_currency best_guess.partial_value / 100.0
    .box-action
      = link_to best_guess_prize_claim_path(best_guess) do
        button.btn.-btn-block.-btn-line-success.-winner Resgatar

- content_for :finished_box, flush: true
  .box-notify.-box-notify-danger
    .box-info.-box-info-notify
      .box-notify-text.u-textUp.u-textBold Pontos Sumatra
    .box-price.-box-price-notify
      span.box-price-big.-box-price-big-notify.js-priceValue = best_guess.final_cost
      .box-notify-discount
        span.u-textBold.js-discount = "Prêmio "
        span.small  Sumatra
    .box-marketValue.u-textBold.u-textCenter
      span.u-textWhite = "valor de mercado: "
      span.u-textWhite = number_to_currency best_guess.market_price
      .box-lastBidder
        .box-lastBidder-name.js-currentWinner = best_guess.winner.try(:username) || best_guess.decorate.last_username
        .box-lastBidder-label Vencedor

- content_for :fail_box, flush: true
  .box-notify.-box-notify-danger
    .box-info.-big.-box-info-notify.-spaced
      i.fa.fa-frown-o
      .box-notify-text Finalizado
    .box-price.-box-price-notify
      span.box-price-small.text-white.u-textBold Infelizmente esse jogo não teve ganhador. Poderia ter sido você, sabia?

.js-box.column.-md-1-3.-sm-1-3.-xs-1-2.-xxs-fill[id="best-guess-#{best_guess.id}" data-verify-url="#{best_guess_verify_status_path(best_guess)}" data-username="#{current_user.try(:username)}"]
  article.box
    .box-badge[class="#{best_guess.tournament? ? '-blue' : '-yellow'}"]
      span.badge-game
        i.fa.fa-badge
        |  #{best_guess.tournament? ? 'Torneio' : 'Sumatra'}
      span.badge-gameType  Palpite
      - if best_guess.tournament?
        span.js-Players
          = " - "
          span = best_guess.best_guess_attempts.count
          | /#{best_guess.players}
    .box-header
      = link_to best_guess_path(best_guess) do
        .box-image[style="background-image: url(#{best_guess.image.url})"]
          .box-image-overlay[class="#{'-small' unless best_guess.scheduled?}"]
            .dynamic-overlay-text
              span.box-image-textBig = best_guess.category
              span.box-image-textSmall = truncate best_guess.question, length: 21
    .box-body
      = link_to best_guess_path(best_guess) do
        h1.box-title.-dynamic.u-textCenter
          span = truncate(best_guess.title, length: 27)

    - if best_guess.scheduled?
      .js-hideScheduledBox
        = content_for :scheduled_box
      .js-hideWinnerBox.u-hide
        = content_for :winner_box
      .js-hideFinishBox.u-hide
        = content_for :finished_box
      .js-hideActiveBox.u-hide
        = content_for :active_box
      .js-hideFailBox.u-hide
        = content_for :fail_box

    - elsif best_guess.active?
      .js-hideActiveBox
        = content_for :active_box
      .js-hideWinnerBox.u-hide
        = content_for :winner_box
      .js-hideFinishBox.u-hide
        = content_for :finished_box
      .js-hideScheduledBox.u-hide
        = content_for :scheduled_box
      .js-hideFailBox.u-hide
        = content_for :fail_box

    - elsif best_guess.finished?
      - if best_guess.sold?
        - if best_guess.winner == current_user
          = content_for :winner_box
        - else
          = content_for :finished_box
      - else
        = content_for :fail_box

.modal-wrapper[id="best-guess-modal-#{best_guess.id}"]
  .modal.-best-guess
    .box-badge.boxCard-badge[class="#{best_guess.tournament? ? '-blue' : '-yellow'}"]
      span.badge-game
        i.fa.fa-badge
        |  Sumatra
      span.badge-gameType  palpite
    .modal-header
      span.modal-close data-close="modal" &times;
      h3.modal-title.u-textCenter = best_guess.title
      table.box-marketValue[style="font-size: 100%; margin-bottom: 19px;width: 100%"]
        tbody
          - if user_signed_in?
            tr
              td
                span Seu saldo:
              td[style="text-align: right"]
                span.u-textYellow.u-textBold
                  |  S
                  i.fa.fa-bitcoin
                  span.js-user-credits = " #{current_user.credits}"
          tr
            td
              span #{best_guess.tournament? ? 'Custo de inscrição' : 'Custo do palpite'}:
            td[style="text-align: right"]
              span.u-textYellow.u-textBold
                |  S
                i.fa.fa-bitcoin
                = " #{best_guess.join_cost_in_credits} "
          tr
            td
              span = 'Valor de mercado: '
            td.text-yellow[style="text-align: right"]
              = number_to_currency best_guess.market_price
          - if !best_guess.tournament?
            tr
              td
                span = 'Valor Atual de Pontos: '
              td.text-yellow[style="text-align: right"]
                = best_guess.partial_value / 100.0

    .modal-body
      .modal-rules
        h5.title Regras do jogo
        dl
          dt Tema
          dd = best_guess.category
        dl
          dt Pergunta (prévia)
          dd = truncate best_guess.question, length: 20
        dl
          dt Termina em
          - if best_guess.tournament?
            dd = "#{pluralize best_guess.duration_time, 'minuto'} após começar"
          - else
            dd = l best_guess.ends_at, format: :long
      - if best_guess.tournament?
        p.u-textCenter[style="color: #888"] Este torneio começa quando #{best_guess.players} jogadores estiverem inscritos
      p.u-textCenter
        label
          | Clicando em Participar você concorda com os termos acima
      .join-in.u-textCenter
        = button_to 'Participar', best_guess_attempts_path(best_guess), class: "btn #{best_guess.tournament? ? '-btn-line-primary' : '-btn-line-secondary'} -btn-block -btn-lg", method: :post

app/views/best_guesses/_feedback.html.slim
- if @best_guess.finished?
  - if @best_guess.winner.present?
    p.text-larger
      span.text-gray Usuário vencedor: 
      strong = @best_guess.winner.try(:username)
    p
      span.text-gray Acertou 
      strong.text-mega = @winner_attempt.score
      span.text-gray  resposta#{'s' if @winner_attempt.score > 1}.
      span.text-gray   Com tempo de 
      strong.text-mega = Time.at(@winner_attempt.finish_time).utc.strftime("%Mm %Ss %3Nms")
    hr
  - if @attempt
    - if @attempt.finish_time
      p.text-larger
        span.text-gray  Você:
        strong  #{current_user.username}
      p
        span.text-gray  Acertou 
        strong.text-mega = @attempt.score
        span.text-gray   resposta#{'s' if @attempt.score > 1}. Seu tempo foi de 
        strong.text-mega = Time.at(@attempt.finish_time).utc.strftime("%Mm %Ss %3Nms")
    - else
      p.text-larger
        span.text-gray  Você:
        strong  não finalizou a tempo
    hr
  p.text-gray Respostas do jogo:
  - @correct_awnsers.each do |statement|
    - if statement.image.present?
      p[style="margin-bottom: 0px"] = image_tag statement.image.url, style: 'max-width: 100%; height: 120px'
    p[style="color: #{statement.answer? ? 'green' : 'red'}"]
      = statement.content
      strong
        |  - #{statement.answer? ? 'Verdadeira' : 'Falso'}

app/views/best_guesses/show.html.slim
.features#highlight
  = render 'highlight', reload: true
.container.-small.u-marginBot100
  .row
    .columns.-md-2-3
      .boxCard[style="padding-top: 0"]
        div[style="padding: 35px"]
          .row.u-marginBot40.js-tabHandle[style="font-size: 0.9em"]
            - if @best_guess.finished?
              .column.-sm-1-4#winnerTab
                button.btn.btn-tab.is-active.-btn-block.js-tab-toggle[data-target="#winner"] Vencedor
            .column.-sm-1-4
              button.btn.btn-tab.-btn-block.js-tab-toggle[data-target="#terms" class="#{'is-active' unless @best_guess.finished?}"] Termos
            - if @best_guess.description
              .column.-sm-1-4
                button.btn.btn-tab.-btn-block.js-tab-toggle data-target="#details" Detalhes
            .column.-sm-1-4
                button.btn.btn-tab.-btn-block.js-tab-toggle data-target="#partners" Parceiros
          .row.js-tabContentHandle
            - if @best_guess.finished?
              .column.-md-fill.js-tab-body.is-open.u-centered#winner
                div[id="gabarito-#{@best_guess.id}"]
                  = render 'feedback'
            .column.-md-fill.js-tab-body.u-centered#terms[class="#{'is-open' unless @best_guess.finished?}"]
              - unless @best_guess.finished?
                div[id="gabarito-#{@best_guess.id}"]
              h1.heading.u-noMarginTop Termos
              .box-marketValue.text-large
                span = "Valor de mercado: "
                span.u-textBold.u-textYellow = number_to_currency @best_guess.market_price
              .box-marketValue.text-large
                span Custo do Palpite:
                span.text-yellow.u-textBold
                  |  S
                  i.fa.fa-bitcoin
                  = " #{@best_guess.join_cost_in_credits} "
              .boxCard-terms
                h5.title Regras do jogo
                dl
                  dt Tema
                  dd = @best_guess.category
                dl
                  dt Pergunta (prévia)
                  dd = truncate @best_guess.question, length: 21
                dl
                  dt Data de término
                  dd
                    - if @best_guess.ends_at
                      = l @best_guess.ends_at, format: :short
                    - else
                      = "#{@best_guess.duration_time} minutos após começar"
            - if @best_guess.description
              .column.-md-fill.js-tab-body.u-centered#details
                h1.heading.u-noMarginTop Detalhes
                p == @best_guess.description
            .column.-md-fill.js-tab-body.u-centered#partners
              h1.heading.u-noMarginTop Parceiros
              = link_to @best_guess.description_url, class: 'btn -btn-line-primary -btn-block -btn-lg', target: :_blank
                | Acesse o site do nosso parceiro
                i.fa.fa-external-link

  .row
    .columns.-md-fill
      .boxCard.u-marginTop100[style="padding-top: 18px; padding-bottom: 10px"]
        = render 'partials/games'