config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get '/busca', to: 'search#games', as: 'search'

  scope path_names: { new: 'novo', edit: 'editar' } do
    get '/auctions/finished', to: 'games#finished_auctions', as: 'finished_auctions', path: 'clicks/finalizados'
    get '/auctions/scheduled', to: 'games#scheduled_auctions', as: 'scheduled_auctions', path: 'clicks/agendados'

    resources :auctions, only: %i(show), path: 'clicks' do
      get :verify_status
      resources :auction_bids, only: %i(create), as: :bids
      get '/prize_claim', to: 'prize_claims#new', as: 'prize_claim', path: 'reivindicar'
    end

    get '/best_guesses/finished', to: 'games#finished_best_guesses', as: 'finished_best_guesses', path: 'super-palpites/finalizados'
    get '/best_guesses/scheduled', to: 'games#scheduled_best_guesses', as: 'scheduled_best_guesses', path: 'super-palpites/agendados'
    get '/super-palpites', to: 'games#best_guesses', as: :best_guesses
    get '/torneio-palpites', to: 'games#best_guess_tournaments', as: :best_guess_tournaments
    get '/super-clicks', to: 'games#auctions', as: :auctions
    get '/torneio-clicks', to: 'games#auction_tournaments', as: :auction_tournaments
    resources :auction_attempts, only: :destroy

    resources :best_guesses, only: %i(show), path: 'super-palpites' do
      get :feedback
      get :unfinished_attempt_redirect
      get :verify_status
      resources :best_guess_attempt, only: %i(create edit update destroy), path: 'tentativas', as: :attempts
      get '/prize_claim', to: 'prize_claims#new', as: 'prize_claim', path: 'reivindicar'
    end

    resources :games, only: :index, path: 'jogos'

    resources :prize_claims, only: %i(create index), as: :prize_claims, path: 'premios'

    if Rails.env.development? || Rails.env.staging?
      get '/styleguide', to: 'pages#styleguide'
    end

    get '/termos', to: 'pages#terms', as: 'terms'
    get '/como-funciona', to: 'pages#how_it_works', as: 'how_it_works'
    get '/contato', to: 'pages#contact', as: 'contact'
    post '/contato', to: 'pages#send_contact', as: nil

    resources :plans, only: %i(index), path: 'planos'
    resources :checkouts, only: %i(new create), path: 'comprar' do
      get :success, path: 'sucesso'
    end
    post "iugu/#{Rails.application.secrets.iugu_url}/notification", to: 'plans#notification', as: nil
    resources :purchases, only: %i(index), path: 'compras'

    devise_for :users, path: "usuarios", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'senha', registration: 'registro', sign_up: 'cadastro' }, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
    devise_scope :user do
      get '/mudar-senha', to: 'users/registrations#edit', as: :change_password
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :purchases

  validates :credits, :price, presence: true
  validates :credits, numericality: { only_integer: true }
  validates :credits, :price, numericality: { greater_than_or_equal_to: 1 }
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: :notification

  before_action :authenticate_user!, except: :notification
  after_action :verify_authorized, except: :notification

  def index
    unless current_user.has_complete_profile?
      redirect_to edit_user_registration_path(to: plans_path), flash: { alert: 'Complete seu perfil primeiro' }
    end
    @plans = Plan.all
    last_purchase = current_user.purchases.last
    @purchase = Purchase.new(
      address: current_user.address || last_purchase.try(:address),
      city: current_user.city || last_purchase.try(:city),
      country: current_user.country || last_purchase.try(:country),
      cpf: current_user.cpf || last_purchase.try(:cpf),
      fullname: current_user.fullname || last_purchase.try(:fullname),
      neighborhood: current_user.neighborhood || last_purchase.try(:neighborhood),
      payment_method: :credit_card,
      phone: current_user.phone || last_purchase.try(:phone),
      plan: @plans[0],
      uf: current_user.uf || last_purchase.try(:uf),
      user: current_user,
      zip_code: current_user.zip_code || last_purchase.try(:zip_code),
    )
    authorize @purchase
  end

  def notification
    handler = Payment::NotificationHandler.new(params)
    handler.perform
    render nothing: true, status: handler.render_status
  end

  private

  def user_not_authorized
    redirect_to edit_user_registration_path, alert: 'Você precisa completar seu perfil para continuar'
  end
end

app/views/plans/_form.html.slim
= simple_form_for @purchase, url: checkouts_path, html: { class: 'js-paymentForm' } do |f|
  = f.input :plan_id, label: false do
    .container
      .js-radio-toggle-wrapper
        .row
          = render partial: 'plans/plan', collection: @plans, locals: { f: f }

  section#plans-payment.plans.features
    .container
      .row
        .column.-md-4-5.u-centered
          h1.heading.-spaced.u-textCenter Pagamento
          h3 Selecione a opção de pagamento
          .paymentMethod.js-radio-toggle-wrapper
            = f.input :payment_method, label: false, collection: Payment::Base.payment_methods, as: :radio_buttons, checked: ["Cartão de Crédito", "credit_card"]
            = f.hidden_field :konduto_user, class: 'js-kondutoUser'

          .js-credit-card-wrapper
            h3 Escolha a opção de pagamento
            .row.-noGutter
              = f.hidden_field :token, readonly: true, size: 64, class: 'js-paymentToken'
              = flash[:charge_messages]
              .column.-md-1-2.planForm-input.ico-cc
                = f.input :cc_number, label: false, placeholder: 'Número do cartão', input_html: { autocomplete: :off, class: '-pays', data: { iugu: :number } }
              .column.-md-1-2.planForm-input.ico-cvv
                = f.input :cc_cvv, label: false, placeholder: 'Código de verificação', input_html: { autocomplete: :off, class: '-pays', data: { iugu: :verification_value } }
              .column.-md-1-2.planForm-input.ico-name
                = f.input :cc_full_name, label: false, placeholder: 'Títular do cartão', input_html: { autocomplete: :off, class: '-pays', data: { iugu: :full_name } }
              .column.-md-1-2.planForm-input.ico-year
                = f.input :cc_expiration, label: false, placeholder: 'MM/AA', input_html: { autocomplete: :off, class: '-pays', data: { iugu: :expiration } }

            h3 Selecione a condição de pagamento
            .row
              .column.-md-1-3
                = f.input :months, label: false, collection: [['1x', 1], ['2x', 2], ['3x', 3]]

          hr.gray

          h3 Confira seus dados de pagamento


          .row.-noGutter
            .column.-md-1-2.planForm-input.u-marginBot10
              = f.input :fullname, input_html: { disabled: f.object.fullname.present? }
            .column.-md-1-2.planForm-input.u-marginBot10
              = f.input :cpf, input_html: { class: 'input-cpf', disabled: f.object.fullname.present? }
            .column.-md-1-2.planForm-input.u-marginBot10
              = f.input :address
            .column.-md-1-2.planForm-input.u-marginBot10
              = f.input :neighborhood
            .column.-md-1-2.planForm-input.u-marginBot10
              = f.input :city
            .column.-md-1-2.planForm-input.u-marginBot10
              = f.input :uf
            .column.-md-1-2.planForm-input.u-marginBot10
              = f.input :country
            .column.-md-1-2.planForm-input.u-marginBot10
              = f.input :zip_code, input_html: { class: 'js-cepMask'}
            .column.-md-1-2.planForm-input.u-marginBot10
              = f.input :phone, input_html: { class: 'js-phoneMask' }

          p.u-marginBot20.text-jumbo.u-textBold.js-price-value
            span.months
            span.text-yellow  parcela(s) de 
            span.price

          = f.submit 'Finalizar compra', class: 'btn -btn-block -btn-line-primary -btn-lg'

app/views/plans/_plan.html.slim
.column.-md-1-3
  label.planBox.js-plan-to-scroll
    = f.radio_button :plan_id, plan.id, class: 'planBox-radio'
    h1.planBox-title = plan.title
    .planBox-price
      span R$
      span.js-plans-cost = number_to_currency plan.price, unit: ''
    .planBox-credits
      span
        | V
        i.fa.fa-bitcoin
      = plan.credits
    .planBox-desc
      | Retorno de
      span  50%
      |  Garantido
    .planBox-action
      a.u-textCenter.btn.-btn-line-primary.-btn-block.-btn-lg type="button" Comprar

app/views/plans/index.html.slim
#iugu-widget[data-account="#{Rails.application.secrets.iugu_account_id}" data-environment="#{Rails.application.secrets.iugu_env}"]


section.features style="background: #f2f2f2;"
  h1.heading.-spaced.u-marginBot80.u-textCenter Comprar créditos
  .container.-small
    .row
      = render 'form'